name: 🚀 On push to main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: 🔖 Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:
    name: 🐳 Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --always --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push api image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/rinha-2026-php:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/rinha-2026-php:latest
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api

      - name: Build and push lb image
        uses: docker/build-push-action@v6
        with:
          context: ./lb
          push: true
          file: ./lb/Dockerfile
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/rinha-2026-php-lb:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/rinha-2026-php-lb:latest
          cache-from: type=gha,scope=lb
          cache-to: type=gha,mode=max,scope=lb
